[build]
  functions = "netlify-lambda-lib"
  command = "npm run download && npm run build"

[[redirects]]
  from = "/.netlify/functions/index"
  to = "/"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 301