[build]
  functions = "netlify-lambda-lib"
  command = "npm run download && npm run build"

[[redirects]]
  from = "/*"
  to = "/"
  status = 301
  
[[redirects]]
  from = "/"
  to = "/.netlify/functions/index"
  status = 200
